[package]
name = "wavetangle"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.16.0"
eframe = "0.33.0"
egui = "0.33.2"
egui-snarl = "0.9.0"
ndarray = "0.17.1"
parking_lot = "0.12"
ringbuf = "0.4"
